### ISSUE TITLE
Compilation of Program.fsx fails with Syntax error at RactiveStatic.makeCustomKeyEvent...

### ISSUE THREAD

**Issue by gdennie** [alfonsogarciacaro/FunScript.Ractive.TodoMVC#1]
Here is the complete error trace preceded by the section of code (Program.fsx, Ln #33), however, other tests isolated the culprit as the pattern: [Value ("enter"), Call (None, RactiveStatic.makeCustomKeyEvent, ...] 

```
let init() =
    // Make the custom key events, the function is based on Rich Harris' code and is defined in FunScript.HTML.Ractive.Extensions
    Globals.Ractive.events.Add("enter", Globals.Ractive.makeCustomKeyEvent(int Keys.enter))
    Globals.Ractive.events.Add("escape", Globals.Ractive.makeCustomKeyEvent(int Keys.escape))
    ......
    ...
```

Error trace...

```
System.Exception: Could not compile expression: Call (Some (Call (None, RactiveStatic.get_events,
                  [Call (None, Globals.get_Ractive.Static, [])])), Add,
      [Value ("enter"),
       Call (None, RactiveStatic.makeCustomKeyEvent,
             [Call (None, Globals.get_Ractive.Static, []),
              Call (None, ToInt, [Value (13.0)])])])
   at FunScript.InternalCompiler.clo@130-1.Invoke(String message)
   at FunScript.ControlFlow.sequential@77-1.Invoke(FSharpExpr _arg1)
   at FunScript.CompilerComponent.create@32.FunScript-InternalCompiler-ICompilerComponent-TryCompile(ICompiler compiler, IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.InternalCompiler.Compiler.tryComponent(IReturnStrategy returnStategy, FSharpExpr expr, ICompilerComponent part)
   at Microsoft.FSharp.Collections.ListModule.TryPick[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list)
   at FunScript.InternalCompiler.Compiler.compile(IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.ReflectedDefinitions.genMethod(MethodBase mb, MethodBase replacementMi, FSharpList`1 vars, FSharpExpr bodyExpr, FSharpVar var, ICompiler compiler)
   at FunScript.ReflectedDefinitions.createGlobalMethod@50.Invoke(FSharpVar var)
   at FunScript.InternalCompiler.Compiler.define(String name, FSharpFunc`2 cons)
   at FunScript.ReflectedDefinitions.createGlobalMethod(String name, ICompiler compiler, MethodBase mb, CallType callType)
   at FunScript.ReflectedDefinitions.createCall[a](FSharpFunc`2 |Split|, IReturnStrategy returnStategy, ICompiler compiler, IEnumerable`1 exprs, MethodInfo mi)
   at FunScript.ReflectedDefinitions.methodCalling@210.Invoke(FSharpFunc`2 split, ICompiler compiler, IReturnStrategy returnStategy, FSharpExpr _arg1)
   at FunScript.CompilerComponent.create@32.FunScript-InternalCompiler-ICompilerComponent-TryCompile(ICompiler compiler, IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.InternalCompiler.Compiler.tryComponent(IReturnStrategy returnStategy, FSharpExpr expr, ICompilerComponent part)
   at Microsoft.FSharp.Collections.ListModule.TryPick[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list)
   at FunScript.InternalCompiler.Compiler.compile(IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.CompilerComponent.splitDeclarationFromUsageIfNeeded(ICompiler compiler, FSharpExpr expr)
   at FunScript.LetBindings.binding@9-1.Invoke(FSharpExpr _arg1)
   at FunScript.CompilerComponent.create@32.FunScript-InternalCompiler-ICompilerComponent-TryCompile(ICompiler compiler, IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.InternalCompiler.Compiler.tryComponent(IReturnStrategy returnStategy, FSharpExpr expr, ICompilerComponent part)
   at Microsoft.FSharp.Collections.ListModule.TryPick[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list)
   at FunScript.InternalCompiler.Compiler.compile(IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.ReflectedDefinitions.genMethod(MethodBase mb, MethodBase replacementMi, FSharpList`1 vars, FSharpExpr bodyExpr, FSharpVar var, ICompiler compiler)
   at FunScript.ReflectedDefinitions.createGlobalMethod@50.Invoke(FSharpVar var)
   at FunScript.InternalCompiler.Compiler.define(String name, FSharpFunc`2 cons)
   at FunScript.ReflectedDefinitions.createGlobalMethod(String name, ICompiler compiler, MethodBase mb, CallType callType)
   at FunScript.ReflectedDefinitions.createCall[a](FSharpFunc`2 |Split|, IReturnStrategy returnStategy, ICompiler compiler, IEnumerable`1 exprs, MethodInfo mi)
   at FunScript.ReflectedDefinitions.methodCalling@210.Invoke(FSharpFunc`2 split, ICompiler compiler, IReturnStrategy returnStategy, FSharpExpr _arg1)
   at FunScript.CompilerComponent.create@32.FunScript-InternalCompiler-ICompilerComponent-TryCompile(ICompiler compiler, IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.InternalCompiler.Compiler.tryComponent(IReturnStrategy returnStategy, FSharpExpr expr, ICompilerComponent part)
   at Microsoft.FSharp.Collections.ListModule.TryPick[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list)
   at FunScript.InternalCompiler.Compiler.compile(IReturnStrategy returnStategy, FSharpExpr expr)
   at FunScript.Compiler.Compiler.Compile(FSharpExpr expression, FSharpOption`1 components, FSharpOption`1 noReturn, FSharpOption`1 shouldFlattenGenericsForReflection, FSharpOption`1 shouldCompress)
   at <StartupCode$FSI_0029>.$FSI_0029.main@() in C:\openSource\FunScript.Ractive.TodoMVC\web\Program.fsx:line 160
Stopped due to error
```

**Comment by gdennie** [comment]
Problem may be related to caching in Visual Studio or perhaps Chrome, though it's cache was disabled. Problem is resolved.
